# Generated by Django 5.1.1 on 2024-12-02 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_annotation_document_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='annotation',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
