# Generated by Django 5.1.1 on 2024-12-14 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_remove_document_is_completed_annotation_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='is_completed',
        ),
    ]
