# Generated by Django 5.1.1 on 2024-12-29 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_remove_annotation_is_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['created_at']},
        ),
    ]
