# Generated by Django 5.1.1 on 2024-12-29 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_alter_document_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['created_at', 'id']},
        ),
    ]
