# Generated by Django 5.1.1 on 2024-12-02 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Annotation',
        ),
    ]
