# Generated by Django 5.1.1 on 2024-12-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_collaborator_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('text classification', 'CLASSIFICATION'), ('sequential labelling', 'SEQUENTIAL')], max_length=100),
        ),
    ]
