# Generated by Django 5.1.1 on 2025-01-01 17:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='invitation_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='joined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
