# Generated by Django 5.1.1 on 2025-01-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_collaborator_invitation_token_collaborator_joined_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='invitation_token',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
