# Generated by Django 5.1.1 on 2025-01-01 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_collaborator_invitation_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborator',
            name='invitation_token',
        ),
    ]
